openapi: 3.0.3
info:
  title: cengage App
  version: 1.0.0
servers:
  - url: https://www.cengage.com
tags:
  - name: api2
  - name: consent
  - name: request
  - name: services
  - name: v1
paths:
  /v1/activity:
    post:
      tags:
        - v1
      summary: POST /v1/activity
      operationId: post_v1_activity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PostRequest"
            examples:
              fromHar:
                value:
                  records:
                    - messageFormatVersion: 1
                      messageType: ClientEventingActivity
                      eventTime: 2026-01-20T11:21:38.044+05:30
                      productEnvironment: production
                      productPlatform: iam-alfred
                      sessionId: 247b7d97-1849-4ac1-ad8f-0bd109921ce6
                      eventId: 77782f52-2624-4eba-808b-b45f3f22f56f
                      eventCategory: UNLOAD
                      eventAction: UNLOAD
                      eventUri: https://account.cengage.com/welcome/iBxTrreMLrkbEJ-JYfVa?email=zubair1digital@gmail.com
                      tags: []
      responses:
        "200":
          description: Success
  /api2/event/cengage_com:
    get:
      tags:
        - api2
      summary: GET /api2/event/cengage_com
      operationId: get_api2_event_cengage_com
      parameters:
        - name: event
          in: query
          required: false
          schema:
            type: string
          example: eyJzb3VyY2UiOnsicGFnZVR5cGUiOiJBY2NvdW50IFBhZ2UiLCJ1cmwiOiJodHRwczovL2FjY291bnQuY2VuZ2FnZS5jb20vd2VsY29tZS9pQnhUcnJlTUxya2JFSi1KWWZWYT9lbWFpbD16dWJhaXIxZGlnaXRhbEBnbWFpbC5jb20iLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYyIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbnltb3VzSWQiOiJiZDlkYjQxZGM1N2U0YWU5IiwiaWRlbnRpdGllcyI6e30sImF0dHJpYnV0ZXMiOnsiY29va2llVVVJRCI6ImJkOWRiNDFkYzU3ZTRhZTkifX0sImludGVyYWN0aW9uIjp7Im5hbWUiOiJWaWV3ZWQgQWNjb3VudCBQYWdlIn0sInBhZ2VWaWV3Ijp0cnVlLCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU3NDY2NzA3MTAwOTA5OTUiLCJleHBsYWluIjp0cnVlfQ==
      responses:
        "200":
          description: Success
  /consent/{id}/c8ff7feb-5a3d-4687-96ed-57769a480d29.json:
    get:
      tags:
        - consent
      summary: GET /consent/{id}/c8ff7feb-5a3d-4687-96ed-57769a480d29.json
      operationId: get_consent_id_c8ff7feb_5a3d_4687_96ed_57769a480d29_json
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: c8ff7feb-5a3d-4687-96ed-57769a480d29
      responses:
        "200":
          description: Success
  /{id}/v1/geo/location:
    get:
      tags:
        - v1
      summary: GET /{id}/v1/geo/location
      operationId: get_id_v1_geo_location
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: cookieconsentpub
      responses:
        "200":
          description: Success
  /request/v1/consentreceipts/anonymous:
    post:
      tags:
        - request
      summary: POST /request/v1/consentreceipts/anonymous
      operationId: post_request_v1_consentreceipts_anonymous
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPostRequest"
            examples:
              fromHar:
                value:
                  requestInformation: eyJhbGciOiJSUzUxMiJ9.eyJvdEp3dFZlcnNpb24iOjEsInByb2Nlc3NJZCI6IjkyMzM0MDQ5LWUyMTAtNGVmNi1iNDI4LTYwYmQwZTg0YzgzYiIsInByb2Nlc3NWZXJzaW9uIjo3LCJpYXQiOiIyMDI1LTA1LTA4VDE1OjE1OjU4LjMwMyIsIm1vYyI6IkNPT0tJRSIsInBvbGljeV91cmkiOiJjZW5nYWdlLmNvbSIsInN1YiI6IkNvb2tpZSBVbmlxdWUgSWQiLCJpc3MiOm51bGwsInRlbmFudElkIjoiZTdlYjcyZTAtMjM2MS00YWQ1LWI1NDgtMjhlN2FhMGQ1YmU4IiwiZGVzY3JpcHRpb24iOiJUaGlzIGNvbGxlY3Rpb24gcG9pbnQgY2FwdHVyZXMgdGhlIGN1cnJlbnQgc2l0ZSB2aXNpdG9yIGNvbnNlbnQgcHJlZmVyZW5jZXMgZm9yIHRoZSBkb21haW46IGNlbmdhZ2UuY29tLWVuIHNwZWNpZmllZC4iLCJjb25zZW50VHlwZSI6IkNPT0tJRUJBTk5FUiIsImFsbG93Tm90R2l2ZW5Db25zZW50cyI6ZmFsc2UsImRvdWJsZU9wdEluIjpmYWxzZSwicHVycG9zZXMiOlt7ImlkIjoiMzVkN2QzMzktNjZiZS00ZjkxLWIxYTktNzQ4YTExYzA5NzZjIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjA2ODQ1OTcxLWJkODQtNDhlMi1hYzZlLTlmMmU0OGQ5OTFjYSIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI3ZTg0ZTMyMC0yMTNjLTRhM2UtOWIxZC00NDA4ZGE2ZWU3ZWMiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMTNkNjE2MzgtN2Q2Ny00ZTY0LWEwMTktMGEwOTEzZDI4MDI0IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjdkMGE5MjU3LTIzZDItNGI4Ni05ZmVmLTdiZTZiZjY5ZjhmOCIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI4MWM1NjZhYi0yYzc2LTQ0YzktOWYwNC1iYzU3NWI0NzM3MzUiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiZTY4ZDhlMTEtODU5NC00NDZmLTgxNGMtMzY0YWU5MDBjM2M5IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjRkMjBhNWMzLTliMzEtNGIwOC05NzExLThiYjYwOWY0ZjM3YSIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiJiYjgzZGZlNS0yM2IzLTQ3MzktOGM3My1mMDMyNmJlZjFhZTUiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMzk0YzVlNTUtOTdjMC00YWFhLThhZmUtZWZkMGRmNmYyOWI5IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjFmZDVhNDgyLTU2ZDctNGNlNS1iMDRiLTc2NmMzNDg0ODEwOSIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI0NThkNjg5NC1hM2FhLTQ2OWUtYWI1My1kMzNmMDNmMzc2M2IiLCJ2ZXJzaW9uIjoyLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiOGE2YzI4ZWQtZWY2Mi00NGZhLTkyYTEtMzI4NGJlZjQ0ZTk2IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6Ijk0NWMzOWM2LWM3ZDEtNDk0Zi05ZmU2LWJjYmZkYTAwMDgxYSIsInZlcnNpb24iOjMsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI4Yzc2MDVlMS0wOTNkLTQyODgtODNmYS0zMjhjY2YxMTk3MTQiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiNjY5M2RiNmQtOWNhMS00OTU4LWI5MjAtNjAyNmVjMmE3MTc2IiwidmVyc2lvbiI6MywicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6ImEwZjFhZDIyLTAxMTUtNGVhYi04MTNiLTJmZTBkMTg2YTM1YyIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiIxNjAyMDllMS02YTZjLTQ2OWEtYTYxNi0wZjMyYjg5ZWY2ZTAiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiZjExMmFiMDctMzFjMS00ZjllLWEwYjAtYTRlZjllOGQyZDA2IiwidmVyc2lvbiI6NSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjBlMTdhMjE4LWYyZDItNGE0NS1iMTU3LWIwYmMzNWU5NThhYiIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiIxNzEwNzhjYi02MGZmLTQwN2ItYTgzOS1lMmQ4MjZmOTBkYzkiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiZTFkNmVhYmMtZjkxNi00NmJhLWI1NGMtZWU4NjBiMjQyYjc3IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjkzZmMyMTYyLTVhNTgtNDJhZi1hNzY5LWE3NjA3NDE0NjkyNCIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiIwMDAyMjBmZS0xYjA4LTQ3OWMtOTU0Zi1kZjU3YzVkMWEwODgiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiN2Q3ZmE4YjgtMjI1My00MjUxLTk0NTMtNmIzOTI1OGM4ZjQwIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjczOTAyMDMwLTYyNTAtNDBhNS1iYzY0LTQzZjVkZWM1ZWIzNSIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiIwOGE2MzM0OS1jOTY1LTQyZmQtYWVhZC1jN2MyZjY1M2I2NmEiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMTQ0NGRmZjctMGQ5Mi00MTdhLWI5ZWEtNzRkYTUxNzY0MWVlIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6ImY2M2FiNzIwLTUzNjAtNDViMC1iMTUwLTNlNzc2ZTA1YTNkMCIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiJiYzZlYTFhMi03YzQ0LTQ4YWMtYjg0Yy03YzAwMDBmZmUyMjMiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMThiNjk5ZDQtMDE2MC00ZWE2LWIwNjctY2UyMGEyOGEyYjVlIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6ImZlMWZkMzJlLTA4YzUtNDRiNS05ZmY4LWQxMDU1ZWYwZDczYyIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiIzNjUyNjg0OC01NjdiLTRiYjMtOGU2NC1kODA0ZGNmN2VjYTYiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMmRiNThmNzEtMTJkNy00ZDZkLWJlNGMtMDg2MTJlMmQ1Y2EwIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjBkYWNkYzI3LWY4NDctNDg4Yy1hMTUwLWRhZjVhYjJjOTQ2YiIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI3MDg2Y2VhYS04NjFmLTRlY2QtOTFlYi0zZjU4OWU2NmY3YjciLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiYzkzMGNhNDMtMDU5Yy00ZmIxLWEyMGItMzM5ZTI2MWMxNjkyIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjdhZWNiM2MyLTE3MDItNGY5ZS04MTI2LWRiYmI1NzZiZjVmMCIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI0ZWJmMjE2NC1hMjZmLTQwYjMtYWZiNC0xMDBkYzgxMDQ1MTciLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiNGYyOGIxZjEtZTFmOC00ZDM0LWE0YjgtZDI4MThjZmI0MjcxIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjRlMjhmZDFiLTAyY2EtNDkyYS1iMTg2LTg4ZWRlZTY1MTkwOSIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI2NjFiNjE0My1jMzExLTRlNzYtODE0ZC0zOTVkNjRlNmY3OTYiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiMjU5MGIyY2ItMjgyNS00MWExLWFmN2ItNzUwNDM0ODA0Y2U3IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6ImNkYTlhY2Y2LWM2NmEtNGVlYy1hZjIwLWM5ZWMyNTdiYTRjOCIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiI5ODg5YWVkZS1lZWY3LTQzN2EtODEzNC00MWZmODVlNTQ0NjQiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiZjI1NTMxODgtYTE0NC00OTdkLWFjNTAtYjkyZGY4MzE3ZjZkIiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH0seyJpZCI6IjgwY2Y5YTE1LTJlNmYtNDQxYy1hNmIyLWYxYTJlMjE3NTBjYyIsInZlcnNpb24iOjEsInBhcmVudElkIjpudWxsLCJ0b3BpY3MiOltdLCJjdXN0b21QcmVmZXJlbmNlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjpmYWxzZSwiaW1wbGljaXRDb25zZW50TGlmZVNwYW4iOjB9LHsiaWQiOiJmZGYwMmQzOC05OTFkLTQ2NTktOTUyNS04MjJkZWI3ZTk3ZDIiLCJ2ZXJzaW9uIjoxLCJwYXJlbnRJZCI6bnVsbCwidG9waWNzIjpbXSwiY3VzdG9tUHJlZmVyZW5jZXMiOltdLCJlbmFibGVHZW9sb2NhdGlvbiI6ZmFsc2UsImltcGxpY2l0Q29uc2VudExpZmVTcGFuIjowfSx7ImlkIjoiYTkyMWRmMDEtYTg4NC00MmNjLThmZmEtN2RmOWI3ZjQ1ZjI1IiwidmVyc2lvbiI6MSwicGFyZW50SWQiOm51bGwsInRvcGljcyI6W10sImN1c3RvbVByZWZlcmVuY2VzIjpbXSwiZW5hYmxlR2VvbG9jYXRpb24iOmZhbHNlLCJpbXBsaWNpdENvbnNlbnRMaWZlU3BhbiI6MH1dLCJub3RpY2VzIjpbXSwiZHNEYXRhRWxlbWVudHMiOlsiVXNlckFnZW50IiwiQ291bnRyeSIsIkludGVyYWN0aW9uVHlwZSIsIkNvbnNlbnRNb2RlbCJdLCJhdXRoZW50aWNhdGlvblJlcXVpcmVkIjpmYWxzZSwicmVjb25maXJtQWN0aXZlUHVycG9zZSI6ZmFsc2UsIm92ZXJyaWRlQWN0aXZlUHVycG9zZSI6dHJ1ZSwiZHluYW1pY0NvbGxlY3Rpb25Qb2ludCI6ZmFsc2UsImFkZGl0aW9uYWxJZGVudGlmaWVycyI6W10sIm11bHRpcGxlSWRlbnRpZmllclR5cGVzIjpmYWxzZSwiZW5hYmxlUGFyZW50UHJpbWFyeUlkZW50aWZpZXJzIjpmYWxzZSwicGFyZW50UHJpbWFyeUlkZW50aWZpZXJzVHlwZSI6bnVsbCwiYWRkaXRpb25hbFBhcmVudElkZW50aWZpZXJUeXBlcyI6W10sImVuYWJsZUdlb2xvY2F0aW9uIjp0cnVlLCJkYXRhRWxlbWVudFR5cGVNYXAiOnsiSW50ZXJhY3Rpb25UeXBlIjoiVVNFUl9JTlBVVCIsIkNvbnNlbnRNb2RlbCI6IlVTRVJfSU5QVVQiLCJVc2VyQWdlbnQiOiJVU0VSX0lOUFVUIiwiQ291bnRyeSI6IlVTRVJfSU5QVVQifX0.KwJMi6-zHkNRkqjLxYCEJn71mt8bF3g0wRgJf5laf1cMGlV2p39bb5Fpl233R_vJONcKY0lnwnmjRiUHx-eLbmWGObBXEWFqFYoN0Jn1msd0jRjFXGPvQ1Yc4GZvxNNz3iX3xo68LHKr3fxFuNUZVE6bYQ9Z544fLseYsYsOCHAmyKur4Vush47NuqYOsEvIMBWHkkx7DBmMR2kjAXGmRJEYE-jpJrg1G2cjajM3N3ANNKmgj9H6UNimk4dyaEXhVSYyzQZsTh-OzMwGE0n-9NLduoQ8vT6bROap6jaLr1g3MWzORYYI46thaw9GIus5k0Xh8Xil1zRGPNp91GRskSl_95B83PodVqxALvokxh0Z7LNPGyj1kvwax0onAGwLC0gNZ45lAg8rGz0aRfX41N-yCJGyaNgLc0RhkqMtQuSxR1QTLtAYL6x7t22NTT8IGeIW_uue3FLBrODoOH9R1xrBSPh5lJDjQ5Jg54cO24OhqRm7goIQY2U7CooNITaH5rDbPEH0ZD_ZEqueg2Sm5oeU7hW24_MUw7ECzJOZP0e0M61tQV8Y68BqlAdKsKI9z7nIUbUEessdLWx3cq1uVR1sJvWi7OtciXZiWwsvXekQauJCYXdMT-tvlLa7PCAZO63AJf2XQMzbjE_T92eXCGp9VLX7uR2uoppCfaobMdY
                  identifier: 494e303e-831a-4348-b746-8f3b7dc99629
                  identifierType: Cookie Unique Id
                  customPayload:
                    Interaction: 2
                    AddDefaultInteraction: false
                  isAnonymous: true
                  test: false
                  purposes:
                    - Id: 6693DB6D-9CA1-4958-B920-6026EC2A7176
                      TransactionType: NO_CHOICE
                    - Id: 945C39C6-C7D1-494F-9FE6-BCBFDA00081A
                      TransactionType: OPT_OUT
                    - Id: F112AB07-31C1-4F9E-A0B0-A4EF9E8D2D06
                      TransactionType: OPT_OUT
                    - Id: 458D6894-A3AA-469E-AB53-D33F03F3763B
                      TransactionType: OPT_OUT
                  dsDataElements: {}
      responses:
        "200":
          description: Success
  /v1/profile:
    post:
      tags:
        - v1
      summary: POST /v1/profile
      operationId: post_v1_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1PostRequest"
            examples:
              fromHar:
                value:
                  records:
                    - messageFormatVersion: 1
                      messageType: ClientEventingProfile
                      productEnvironment: production
                      productPlatform: iam-alfred
                      sessionId: 478852a6-638b-4287-9277-3ac96ecf8e9a
                      eventTime: 2026-01-20T11:21:53.700+05:30
                      platform:
                        userAgentString: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0
                          Safari/537.36
                        browserFingerprint: 6419da8004f96663795183d397b5dc8d
                        browserName: Chrome
                        browserVersion: 144.0.0.0
                        osName: Windows
                        osVersion: NT 10.0
                        osVersionName: "10"
                        engineName: Blink
                        platformType: desktop
                        language: en-US
                        screenResolution:
                          width: 1366
                          height: 768
                      location:
                        timeZone: Asia/Calcutta
      responses:
        "200":
          description: Success
  /services/stx/bff/context:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/context
      operationId: get_services_stx_bff_context
      responses:
        "200":
          description: Success
    options:
      tags:
        - services
      summary: OPTIONS /services/stx/bff/context
      operationId: options_services_stx_bff_context
      responses:
        "200":
          description: Success
  /services/{id}/bff/version:
    get:
      tags:
        - services
      summary: GET /services/{id}/bff/version
      operationId: get_services_id_bff_version
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: universal-sidebar
      responses:
        "200":
          description: Success
  /services/{id}/bff/configs:
    get:
      tags:
        - services
      summary: GET /services/{id}/bff/configs
      operationId: get_services_id_bff_configs
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: universal-sidebar
      responses:
        "200":
          description: Success
  /services/stx/bff/{id}:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/{id}
      operationId: get_services_stx_bff_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: entitlement-tiles
      responses:
        "200":
          description: Success
  /services/stx/bff/search/products/config:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/search/products/config
      operationId: get_services_stx_bff_search_products_config
      responses:
        "200":
          description: Success
  /services/{id}/bff/currentUser:
    get:
      tags:
        - services
      summary: GET /services/{id}/bff/currentUser
      operationId: get_services_id_bff_currentUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: universal-sidebar
      responses:
        "200":
          description: Success
  /services/{id}/bff/elements:
    get:
      tags:
        - services
      summary: GET /services/{id}/bff/elements
      operationId: get_services_id_bff_elements
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: universal-sidebar
      responses:
        "200":
          description: Success
  /services/stx/bff/pin/all:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/pin/all
      operationId: get_services_stx_bff_pin_all
      responses:
        "200":
          description: Success
  /services/ipm/bff/prebind:
    post:
      tags:
        - services
      summary: POST /services/ipm/bff/prebind
      operationId: post_services_ipm_bff_prebind
      responses:
        "200":
          description: Success
  /services/ipm/xmpp/bind:
    post:
      tags:
        - services
      summary: POST /services/ipm/xmpp/bind
      operationId: post_services_ipm_xmpp_bind
      requestBody:
        required: true
        content:
          text/xml:
            schema:
              type: string
            examples:
              fromHar:
                value: <body xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" rid="8476785" sid="7gfzti7wa0"><iq
                  xmlns="jabber:client" type="get" id="48f924e6-4104-4f0c-b5bf-5309b0dde602"><offline
                  xmlns="http://jabber.org/protocol/offline"><fetch/></offline></iq></body>
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/{id}:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/{id}
      operationId: post_services_stx_bff_registerCode_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: ABC1D-EF23G-HI45J
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/MTP9X222A7B3:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/MTP9X222A7B3
      operationId: post_services_stx_bff_registerCode_MTP9X222A7B3
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/MTP9X222A7B4:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/MTP9X222A7B4
      operationId: post_services_stx_bff_registerCode_MTP9X222A7B4
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/MTP9X222A7B5:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/MTP9X222A7B5
      operationId: post_services_stx_bff_registerCode_MTP9X222A7B5
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/MTP9X222A7B6:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/MTP9X222A7B6
      operationId: post_services_stx_bff_registerCode_MTP9X222A7B6
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/Artificial%20intelligence:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/Artificial%20intelligence
      operationId: post_services_stx_bff_registerCode_Artificial_20intelligence
      parameters:
        - name: modelType
          in: query
          required: false
          schema:
            type: string
          example: COURSE_KEY
      responses:
        "200":
          description: Success
  /services/stx/bff/registerCode/MYSCHOOL%201234%205678:
    post:
      tags:
        - services
      summary: POST /services/stx/bff/registerCode/MYSCHOOL%201234%205678
      operationId: post_services_stx_bff_registerCode_MYSCHOOL_201234_205678
      parameters:
        - name: modelType
          in: query
          required: false
          schema:
            type: string
          example: COURSE_KEY
      responses:
        "200":
          description: Success
  /services/stx/bff/studyPacks/generalInfo:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/studyPacks/generalInfo
      operationId: get_services_stx_bff_studyPacks_generalInfo
      responses:
        "200":
          description: Success
  /services/stx/bff/studyTools:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/studyTools
      operationId: get_services_stx_bff_studyTools
      responses:
        "200":
          description: Success
  /services/stx/bff/studyPacks/byCgi/{id}:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/studyPacks/byCgi/{id}
      operationId: get_services_stx_bff_studyPacks_byCgi_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: SEMSKF68FX1FGP3ST235
      responses:
        "200":
          description: Success
  /services/stx/bff/pin/cgi/{id}:
    get:
      tags:
        - services
      summary: GET /services/stx/bff/pin/cgi/{id}
      operationId: get_services_stx_bff_pin_cgi_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: SEMSKF68FX1FGP3ST235
      responses:
        "200":
          description: Success
    post:
      tags:
        - services
      summary: POST /services/stx/bff/pin/cgi/{id}
      operationId: post_services_stx_bff_pin_cgi_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: SEMSKF68FX1FGP3ST235
      responses:
        "200":
          description: Success
components:
  schemas:
    V1PostRequest:
      type: object
      properties:
        records:
          type: array
          items:
            type: object
            properties:
              messageFormatVersion:
                type: integer
              messageType:
                type: string
              eventTime:
                type: string
              productEnvironment:
                type: string
              productPlatform:
                type: string
              sessionId:
                type: string
              eventId:
                type: string
              eventCategory:
                type: string
              eventAction:
                type: string
              eventUri:
                type: string
              tags:
                type: array
                items:
                  type: string
            required:
              - messageFormatVersion
              - messageType
              - eventTime
              - productEnvironment
              - productPlatform
              - sessionId
              - eventId
              - eventCategory
              - eventAction
              - eventUri
              - tags
      required:
        - records
    RequestPostRequest:
      type: object
      properties:
        requestInformation:
          type: string
        identifier:
          type: string
        identifierType:
          type: string
        customPayload:
          type: object
          properties:
            Interaction:
              type: integer
            AddDefaultInteraction:
              type: boolean
          required:
            - Interaction
            - AddDefaultInteraction
        isAnonymous:
          type: boolean
        test:
          type: boolean
        purposes:
          type: array
          items:
            type: object
            properties:
              Id:
                type: string
              TransactionType:
                type: string
            required:
              - Id
              - TransactionType
        dsDataElements:
          type: object
          properties: {}
         
      required:
        - requestInformation
        - identifier
        - identifierType
        - customPayload
        - isAnonymous
        - test
        - purposes
        - dsDataElements
