openapi: 3.0.3
info:
  title: Uber Eats 3
  version: 1.0.0
servers:
  - url: https://www.ubereats.com
tags:
  - name: allStoresV1
  - name: getFeedByIdV1
  - name: getFeedV1
  - name: getMenuItemV1
  - name: getSearchFeedV1
  - name: getSearchHomeV2
  - name: getStoreV1
  - name: getUserV1
  - name: udiMetaV1
  - name: "{id}"
paths:
  /_p/api/{id}:
    post:
      tags:
        - "{id}"
      summary: POST /_p/api/{id}
      operationId: post__p_api_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: setRobotEventsV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/{id}PostRequest"
            examples:
              fromHar:
                value:
                  action: rendered
                  payload:
                    shouldIndex: false
                    shouldIndexOverride: true
                    appVariant: eats
                    overrideAvoided: false
                    isBot: false
                    page: unknown
      responses:
        "200":
          description: Success
  /_p/api/getUserV1:
    post:
      tags:
        - getUserV1
      summary: POST /_p/api/getUserV1
      operationId: post__p_api_getUserV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetUserV1PostRequest"
            examples:
              fromHar:
                value:
                  shouldGetSubsMetadata: true
      responses:
        "200":
          description: Success
  /_p/api/getSearchHomeV2:
    post:
      tags:
        - getSearchHomeV2
      summary: POST /_p/api/getSearchHomeV2
      operationId: post__p_api_getSearchHomeV2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetSearchHomeV2PostRequest"
            examples:
              fromHar:
                value:
                  dropPastOrders: true
      responses:
        "200":
          description: Success
  /_p/api/getFeedByIdV1:
    post:
      tags:
        - getFeedByIdV1
      summary: POST /_p/api/getFeedByIdV1
      operationId: post__p_api_getFeedByIdV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFeedByIdV1PostRequest"
            examples:
              fromHar:
                value:
                  feedID: convenience_feed
                  deliveryLocation:
                    - type: USER
                    - type: GEOIP
                  feedmakerCtx: ""
      responses:
        "200":
          description: Success
  /_p/api/allStoresV1:
    post:
      tags:
        - allStoresV1
      summary: POST /_p/api/allStoresV1
      operationId: post__p_api_allStoresV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AllStoresV1PostRequest"
            examples:
              fromHar:
                value:
                  date: ""
                  startTime: 0
                  endTime: 0
                  sortAndFilters:
                    - uuid: f744706c-2b1b-4db2-b40a-13d43cb338da
                      options:
                        - uuid: 13ce1932-1878-4e2e-80d0-5760c095c641
                  surfaceName: HOME
                  cacheKey: ""
                  verticalType: ""
      responses:
        "200":
          description: Success
  /_p/api/getFeedV1:
    post:
      tags:
        - getFeedV1
      summary: POST /_p/api/getFeedV1
      operationId: post__p_api_getFeedV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFeedV1PostRequest"
            examples:
              fromHar:
                value:
                  cacheKey: /DELIVERY///0/0//JTVCJTVE/undefined//////HOME/SHOP///////
                  feedSessionCount:
                    announcementCount: 0
                    announcementLabel: ""
                  userQuery: ""
                  date: ""
                  startTime: 0
                  endTime: 0
                  carouselId: ""
                  sortAndFilters: []
                  billboardUuid: ""
                  feedProvider: ""
                  promotionUuid: ""
                  targetingStoreTag: ""
                  venueUUID: ""
                  selectedSectionUUID: ""
                  favorites: ""
                  vertical: ""
                  searchSource: ""
                  searchType: ""
                  keyName: ""
                  serializedRequestContext: ""
                  verticalType: SHOP
                  isUserInitiatedRefresh: false
      responses:
        "200":
          description: Success
  /_p/api/getSearchFeedV1:
    post:
      tags:
        - getSearchFeedV1
      summary: POST /_p/api/getSearchFeedV1
      operationId: post__p_api_getSearchFeedV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetSearchFeedV1PostRequest"
            examples:
              fromHar:
                value:
                  userQuery: Halal
                  date: ""
                  startTime: 0
                  endTime: 0
                  sortAndFilters: []
                  vertical: ""
                  searchSource: HOME_FEED_FILTER
                  displayType: SEARCH_RESULTS
                  searchType: ""
                  keyName: ""
                  cacheKey: ""
                  recaptchaToken: ""
      responses:
        "200":
          description: Success
  /_p/api/getStoreV1:
    post:
      tags:
        - getStoreV1
      summary: POST /_p/api/getStoreV1
      operationId: post__p_api_getStoreV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetStoreV1PostRequest"
            examples:
              fromHar:
                value:
                  storeUuid: d937e7af-e1c9-554f-9426-2a5ef722b565
                  diningMode: DELIVERY
                  time:
                    asap: true
                  cbType: EATER_ENDORSED
      responses:
        "200":
          description: Success
  /_p/api/getMenuItemV1:
    post:
      tags:
        - getMenuItemV1
      summary: POST /_p/api/getMenuItemV1
      operationId: post__p_api_getMenuItemV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetMenuItemV1PostRequest"
            examples:
              fromHar:
                value:
                  itemRequestType: ITEM
                  storeUuid: d937e7af-e1c9-554f-9426-2a5ef722b565
                  sectionUuid: 0617e935-621e-4dce-9e9a-ac217f5c0142
                  subsectionUuid: 0379a62a-1156-4ddb-a09a-7e1dc45d5dfb
                  menuItemUuid: 5ac93198-0a16-436f-9e8c-d080de743be7
                  cbType: EATER_ENDORSED
                  includeCheaperAlternatives: false
                  contextReferences:
                    - type: GROUP_ITEMS
                      payload:
                        type: groupItemsContextReferencePayload
                        groupItemsContextReferencePayload: {}
                      pageContext: STORE
      responses:
        "200":
          description: Success
  /_p/api/udiMetaV1:
    post:
      tags:
        - udiMetaV1
      summary: POST /_p/api/udiMetaV1
      operationId: post__p_api_udiMetaV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UdiMetaV1PostRequest"
            examples:
              fromHar:
                value:
                  meta: IsOFwpJePcOFw5sVO8KFwoIBb8OWw5QPbMKEw5UFbcOXw5YFe8OLw4NoLcOFw5sVGMKDwpUBGMKQwoUBI8K9w5RnOMOUwqxvb8Kewq9gYcKWwpMAdsK3w5BtFcKEwo9NFcKlwrh5DcKFwqgDFsKowrkAYMK3wqx7NMKmwrdkIMKEw5hHaMKmwrtlHsK+wqZzb8KIw5R/I8Ofw5JEMcOUwpZBEsKWwrB2aMKkwodDE8KOwo1CDMOIwqdPNsKIwqxiLsK1wqx0YcKtwosBC8KKwo9TaMOTwoZZF8KXw5FECsKjwqVtLcKmwrhvP8KSwopFbsKOw5laOMORwoJFF8K3woRyacKFwptiLcORw5ZWIcKjwqhHF8K3wqtVDcKxwqpnKcKswrVyaMOWwrgDFsOWw5IFM8Kuw5JbE8KFwqkAa8KSw5RDcsOVwpN5AMK0wpVbEMKiwoZQacOIwoZnCsOIwpN5CcKAw5FfN8KkwpttPcK2wosBcsOSw5FcN8KTwogAaMOVwplRAcKywo1DG8OUwoNyFMKQwqgDPsKRw4pUMMKpwoMDFcKQwphVA8KRwrh1KMKGwpdQFsKow5YYMMK3wqt9D8KiwoIAKsKWw5J/AMK1wogDHcKewrEBNMORwrdwA8OIwq5DHsKgw5ZWbsOSwpB0dsOQwpZ7acKow5Z+I8OWwqdxIMOVwptxYcKxwoJDNsKSw5dQbsKywo5vAcK0wqZFCMOIwpR1csKMwrRdL8OTwoIYK8OTw5BPEMOXwrBNEsKiwoYKe8OLw4NUP8K4wodbOMKAwpIVY8OFw5AHa8OVw5gBasOFw40VP8KVwoREMcOKwoJYNsKMwohSe8Odw4NDK8KSwoQVdcOFwoJYNsKMwohSdMK4woJUe8Odw4N2PcKTw5d2LsKDw5dNA8OSwrFWasKqwrkBIMKpwrYPKMKVw5YVdcOFwoJYNsKMwohSdMK4woJePcK4woJUe8Odw4N2PcKTw5d2LsKDw5dNA8OSwrFWasKqwrkBIMKpwrYPKMKVw5YVdcOFwpVeNMKCw4xCN8KOwpkaPMKXwo5UMcOKwoxEe8Odw5AAb8Oew5IObsOew5UOaMOWw5Ybe8KTwohaPMOKwo1YOsKGwo0VY8OFw5AYa8ORw44FacOVw5cbecOfw5sCbMOdw5UOecKmwqwVdcOFwpVeNMKCw4xELcKVwohZPsOFw5sVFMKIwo8XE8KGwo8Xa8ORw4EFacOVw5cXacOfw5sCbMOdw5UOecKgwqxjcsOXw5QEacOHw4l+N8KDwohWecK0wpVWN8KDwoBFPcOHwrVeNMKCw4gVdcOFwpVeNMKCw4xDI8OKwo5RP8KUwoRDdMKKwohZLMKTwoREe8Odw4wEasOXw40VLcKOwoxSdMKTwpsaMcKGwpIaPcKUwpUVY8OFwodWNcKUwoQVdcOFwpVeNMKCw4xDI8OKwoVELcOKwoBULcKOwpdSe8Odw4NROMKLwpJSe8OLw4NDMMKKwoQaLcKdw4xELcKDw4xYP8KBwpJSLcOFw5saasOUw5Ebe8KTwohaPMOKwpVNdMKBwohPPMKDw4xbNsKEwoBbPMOKwpJDK8KOwo9Qe8Odw4MEdsORw44FacOWw5UbecOQw5sCYcOdw5IOecKmwqwVdcOFwoVYNMOKwo1YOsKGwo0aLcKGwoYVY8OFwqBTLcORwqBAPcORwpttbMK3woAEFMK/w5dOF8Kww5lGK8OQw4Mbe8KEwohTdMKDwo5adMKLwo5UOMKLw4xDOMKAw4MNe8KmwoVDb8KmwpZTb8KdwrsCCcKGw5J6AcORwph5DsOfwpBFbsOFw40VPcKIwowaKsKCwpJEMMKIwo8aLcKGwoYVY8OFwqBTLcORwqBAPcORwpttbMK3woAEFMK/w5dOF8Kww5lGK8OQw4Mbe8KEwohTdMKDwo5adMKUwoREKsKOwo5ZdMKTwoBQe8Odw4N2PcKTw5d2LsKDw5dNA8OSwrFWasKqwrkBIMKpwrYPKMKVw5YVdcOFwo9WL8KOwoZWLcKIwpMZLMKUwoRFGMKAwoRZLcKjwoBDOMOJwoNFOMKJwoVEe8OdwrpMe8KFwpNWN8KDw4MNe8Kpwo5DccKmw5t1K8KGwo9Te8OLw4NBPMKVwpJeNsKJw4MNe8Ofw4NKdcKcw4NVK8KGwo9Te8Odw4N0McKVwo5aMMKSwowVdcOFwpdSK8KUwohYN8OFw5sVaMOTw5UVJMOLwpoVO8KVwoBZPcOFw5sVHsKIwo5QNcKCw4F0McKVwo5aPMOFw40VL8KCwpNEMMKIwo8VY8OFw5ADbcOFwpxqdcOFwo9WL8KOwoZWLcKIwpMZLMKUwoRFGMKAwoRZLcKjwoBDOMOJwoxYO8KOwo1Se8OdwodWNcKUwoQbe8KJwoBBMMKAwoBDNsKVw49CKsKCwpN2PsKCwo9DHcKGwpVWd8KXwo1WLcKBwo5FNMOFw5sVDsKOwo9TNsKQwpIVdcOFwo9WL8KOwoZWLcKIwpMZOMKXwpFhPMKVwpJeNsKJw4MNe8OSw48HecOPwrZeN8KDwo5AKsOHwq9jecOWw5EZacOcw4FgMMKJw5cDYsOHwpkBbcOOw4F2KcKXwo1SDsKCwoN8MMKTw44CasOQw48Eb8OHw4l8EcKzwqx7dcOHwo1eMsKCw4FwPMKEwopYcMOHwqJfK8KIwoxSdsOWw5UDd8OXw48Hd8OXw4FkOMKBwoBFMMOIw5QEbsOJw5IBe8OLw4NZOMKRwohQOMKTwo5Fd8KGwpFHF8KGwoxSe8Odw4N5PMKTwpJUOMKXwoQVdcOFwo9WL8KOwoZWLcKIwpMZKcKVwo5TLMKEwpUVY8OFwqZSOsKMwo4VdcOFwo9WL8KOwoZWLcKIwpMZKcKLwoBDP8KIwpNae8Odw4NgMMKJw5IFe8OLw4NZOMKRwohQOMKTwo5Fd8KLwoBZPsKSwoBQPMOFw5sVPMKJw4xwG8OFw40VN8KGwpdePsKGwpVYK8OJwpREPMKVwqBQPMKJwpUVY8OFwqxYI8KOwo1bOMOIw5QZacOHw4lgMMKJwoVYLsKUw4F5DcOHw5AHd8OXw5oXDsKOwo8BbcOcw4FPb8OTw4gXGMKXwpFbPMKwwoRVEsKOwpUYbMOUw5YZasORw4EfEsKvwrV6FcOLw4FbMMKMwoQXHsKCwoJcNsOOw4F0McKVwo5aPMOIw5ADbcOJw5EZacOJw5EXCsKGwodWK8KOw44CasOQw48Eb8OFw40VN8KGwpdePsKGwpVYK8OJwoJYNsKMwohSHMKJwoBVNcKCwoUVY8OFwpVFLMKCw4Mbe8KJwoBBMMKAwoBDNsKVw49WKcKXwqJYPcKCwq9WNMKCw4MNe8Kqwo5NMMKLwo1We8OLw4NZOMKRwohQOMKTwo5Fd8KRwoRZPcKIwpMVY8OFwqZYNsKAwo1SecKuwo9Ud8OFw40VN8KGwpdePsKGwpVYK8OJwpFFNsKDwpRULcK0wpRVe8Odw4MFacOXw5IHaMOXw5YVdcOFwo9WL8KOwoZWLcKIwpMZMcKGwpNTLsKGwpNSGsKIwo9ULMKVwpNSN8KEwpgVY8OFw5UVdcOFwo9WL8KOwoZWLcKIwpMZPcKCwpdeOsKCwqxSNMKIwpNOe8Odw4MPe8OLw4NZOMKRwohQOMKTwo5Fd8KEwo5ZN8KCwoJDMMKIwo8ZPMKBwodSOsKTwohBPMKzwphHPMOFw5sVbcKAw4Mbe8KJwoBBMMKAwoBDNsKVw49UNsKJwo9SOsKTwohYN8OJwpNDLcOFw5sCacOLw4NZOMKRwohQOMKTwo5Fd8KEwo5ZN8KCwoJDMMKIwo8ZKsKGwpdSHcKGwpVWe8OdwodWNcKUwoQbe8KTwo5COsKPwqRZOMKFwo1SPcOFw5tROMKLwpJSdcOFwo9WL8KOwoZWLcKIwpMZOMKSwpVYNMKGwpVeNsKJwqRZOMKFwo1SPcOFw5tROMKLwpJSdcOFwo9WL8KOwoZWLcKIwpMZPcKIwq9YLcKzwpNWOsKMw4MNe8OFw40VLsKCwoNTK8KOwpdSK8K4woVSLcKCwoJDe8OdwodWNcKUwoQbe8KQwohZPcKIwpYZKsKEwpNSPMKJw49UNsKLwo5FHcKCwpFDMcOFw5sVa8OTw4Mbe8KQwohZPcKIwpYZOsKLwohSN8KTwqhZP8KIwpNaOMKTwohYN8OJwo1WN8KAwpRWPsKCw4MNe8KCwo8aHsKlw4Mbe8KQwohZPcKIwpYZKsKEwpNSPMKJw49HMMKfwoRbHcKCwpFDMcOFw5sVa8OTw4Mbe8KQwohZPcKIwpYZMcKOwpJDNsKVwpgZNcKCwo9QLcKPw4MNe8OWw5kVdcOFwpZeN8KDwo5Ad8KDwoRBMMKEwoRnMMKfwoRbC8KGwpVeNsOFw5sVaMOFw40VLsKOwo9TNsKQw49EOsKVwoRSN8OJwolSMMKAwolDe8Odw4MAb8Ofw4Mbe8KQwohZPcKIwpYZKsKEwpNSPMKJw49AMMKDwpVfe8Odw4MGasORw5cVdcOFwpZeN8KDwo5Ad8KUwoJFPMKCwo8ZOMKRwoBeNcKvwoRePsKPwpUVY8OFw5YFacOFw40VLsKOwo9TNsKQw49YLMKTwoRFDsKOwoVDMcOFw5sVaMOUw5cBe8OLw4NAMMKJwoVYLsOJwo5CLcKCwpN/PMKOwoZfLcOFw5sVbsOVw5EVdcOFwpZeN8KDwo5Ad8KOwo9ZPMKVwrZePcKTwokVY8OFw5AGaMOVw4Mbe8KQwohZPcKIwpYZMMKJwo9SK8KvwoRePsKPwpUVY8OFw5QOYMOFw40VKsKEwpNSPMKJw49WL8KGwohbDsKOwoVDMcOFw5sVaMOUw5cBe8OLw4NEOsKVwoRSN8OJwoBBOMKOwo1/PMKOwoZfLcOFw5sVbsOVw5EVdcOFwpZeN8KDwo5Ad8KUwoJFPMKCwo8ZNsKVwohSN8KTwoBDMMKIwo8ZLcKewpFSe8Odw4NbOMKJwoVEOsKGwpFSdMKXwpNeNMKGwpNOe8OLw4NAMMKJwoVYLsOJwpJUK8KCwoRZd8KIwpNePMKJwpVWLcKOwo5Zd8KGwo9QNcKCw4MNe8OXw4Mbe8KQwohZPcKIwpYZKsKEwpNSPMKJw49TOMKVwop6NsKDwoQZPMKJwoBVNcKCwoUVY8KTwpNCPMOLw4NHNcKSwoZeN8OKwrFzH8OHwrdePMKQwoRFdMKBwohbPMKJwoBaPMOFw5sVMMKJwpVSK8KJwoBbdMKXwoVRdMKRwohSLsKCwpMVdcOFwpFbLMKAwohZdMK3wqVxecKxwohSLsKCwpMaPcKCwpJUe8Odw4NnNsKVwpVWO8KLwoQXHcKIwoJCNMKCwo9DecKhwo5FNMKGwpUVdcOFwpFbLMKAwohZdMKkwolFNsKKwoQXCcKjwqcXD8KOwoRAPMKVw4xRMMKLwoRZOMKKwoQVY8OFwohZLcKCwpNZOMKLw4xHPcKBw4xBMMKCwpZSK8OFw40VKcKLwpRQMMKJw4x0McKVwo5aPMOHwrFzH8OHwrdePMKQwoRFdMKDwoREOsOFw5sVCcKIwpNDOMKFwo1SecKjwo5ULMKKwoRZLcOHwqdYK8KKwoBDe8OLw4NHNcKSwoZeN8OKwqJfK8KIwoxeLMKKw4FnHcKhw4FhMMKCwpZSK8OKwodeNcKCwo9WNMKCw4MNe8KOwo9DPMKVwo9WNcOKwpFTP8OKwpdePMKQwoRFe8OLw4NHNcKSwoZeN8OKwqJfK8KIwoxeLMKKw4FnHcKhw4FhMMKCwpZSK8OKwoVSKsKEw4MNe8K3wo5FLcKGwoNbPMOHwqVYOsKSwoxSN8KTw4FxNsKVwoxWLcOFw40VKcKLwpRQMMKJw4x6MMKEwpNYKsKIwodDecKiwoVQPMOHwrFzH8OHwrdePMKQwoRFdMKBwohbPMKJwoBaPMOFw5sVMMKJwpVSK8KJwoBbdMKXwoVRdMKRwohSLsKCwpMVdcOFwpFbLMKAwohZdMKqwohUK8KIwpJYP8KTw4FyPcKAwoQXCcKjwqcXD8KOwoRAPMKVw4xTPMKUwoIVY8OFwrFYK8KTwoBVNcKCw4FzNsKEwpRaPMKJwpUXH8KIwpNaOMKTw4Mbe8KXwo1CPsKOwo8aDsKCwoN8MMKTw4FVLMKOwo1DdMKOwo8XCcKjwqcaP8KOwo1SN8KGwoxSe8Odw4NeN8KTwoRFN8KGwo0aKcKDwocaL8KOwoRAPMKVw4Mbe8KXwo1CPsKOwo8aDsKCwoN8MMKTw4FVLMKOwo1DdMKOwo8XCcKjwqcaPcKCwpJUe8Odw4NnNsKVwpVWO8KLwoQXHcKIwoJCNMKCwo9DecKhwo5FNMKGwpUVdcOFwoJWN8KRwoBEdMKXwpNeN8KTw4wGacOXw4wOYMOew4MNe8KDwoAHbsOfw5NTYMOVw5QBasOQw5kDasOTw5UFaMOXwoQPYcOQw5ZVOsOfw5AGbsKCw5JTbcOVw5IHO8OFw40VOsKGwo9BOMKUw4xHK8KOwo9DdMKDwoRDOMKOwo1SPcOKw5AHacOKw5gOYMOFw5sVP8ORw5MHP8KEw5cFPMOWw5cEOMOewoBRPMOWwoACa8KDwoUPPMKBw5IPYcKGw5kBbMKEw5AGasKCw5RVe8OLw4NUOMKJwpdWKsK4wpJHNsKIwodeN8KAw4MNacOLw4NdKsOKwoRFK8KIwpNEe8OdwroVEMKJwpdWNcKOwoV0McKGwpNWOsKTwoRFHMKVwpNYK8Odw4FxOMKOwo1SPcOHwpVYecKCwplSOsKSwpVSecOAwoJFPMKGwpVSHMKLwoRaPMKJwpUQecKIwo8XfsKjwo5ULMKKwoRZLcOAw5sXDcKPwoQXLcKGwoYXN8KGwoxSecKXwpNYL8KOwoVSPcOHw4kQZcKIwoNdPMKEwpUXMMKDw5xre8KDwohWNcKIwoZ/PMKLwpFSK8KuwoVre8OHwoJbOMKUwpJePcOawr0VOsKLwpJePcOdw5IHbMOXwocPaMOew4wOYcKFw5QaaMOWwoJRdMKFwoMPa8OKw5EHOMKGw5EHO8KDwoJSacKFwr0VecKQwohTLcKPw5xre8OXwr0VecKPwoRePsKPwpUKBcOFw5Fre8OZw50YNsKFwotSOsKTw58QcMOHwohEecKJwo5DecKGw4FBOMKLwohTecKJwoBaPMOJw4NqdcOFwodYN8KTw4xjMMKKwoREecKpwoRAecK1wo5aOMKJw4F0AMK1w4MNP8KGwo1EPMOLw4NRNsKJwpUaGMKVwohWNcOHwqJuC8OFw5tROMKLwpJSdcOFwodYN8KTw4x0NsKSwpNePMKVw4F5PMKQw4F0AMK1w4MNP8KGwo1EPMOLw4NRNsKJwpUa776k77ya77yc77+K776k77yaw4MNP8KGwo1EPMOLw4NRNsKJwpUaGMKVwohWNcOHwqJOK8OFw5tROMKLwpJSdcOFwodYN8KTw4xjMMKKwoREecKpwoRAecK1wo5aOMKJw4F0IMKVw4MNP8KGwo1EPMOLw4NRNsKJwpUaGsKIwpRFMMKCwpMXF8KCwpYXGsKewpMVY8KBwoBbKsKCw40VP8KIwo9DdO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pMOFw5tROMKLwpJSdcOFwodYN8KTw4zvv4rvvqTvvJrvvJzvv4rvvqTDh8KxRTbDhcObUTjCi8KSUnXDhcKHWDfCk8OMYAnDh8KiTivCjsKNWzDChMKjFWPCgcKAWyrCgsONFT/CiMKPQ3TCsMKxFxrCnsKTXjXCi8KIVBjDhcObUTjCi8KSUnXDhcKHWDfCk8OM77+K776k77ya77yc77+K776k77ya77yc77+Ke8OdwodWNcKUwoQbe8KBwo5ZLcOK77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77yaw4FnK8ORwq8XG8OFw5tROMKLwpJSdcOFwodYN8KTw4zvv4rvvqTvvJrvvJzvv4rvvqTDisKxYhjDhcObUTjCi8KSUnXDhcKHWDfCk8OM77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+Ke8OdwodWNcKUwoQbe8KBwo5ZLcOK77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+Ke8OdwodWNcKUwoQbe8KBwo5ZLcOKwqZWK8KGwoxYN8KDwq9YbcKkwphFDcKkwrh7MMKAw4MNP8KGwo1EPMOLw4NRNsKJwpUaEcKCwo1BPMKTwohUOMKuwo9EPMKVwoBDGsKewpMXDMKXwpNePsKPwpUVY8KBwoBbKsKCw40VP8KIwo9DdMKvwoRbL8KCwpVeOsKGwqJOK8OHwrRHK8KOwoZfLcOFw5tROMKLwpJSdcOFwodYN8KTw4xjFcOHwqlSNcKXw4F0IMKVwohbNcKOwoIVY8KBwoBbKsKCw40VP8KIwo9DdMKzwq10IMKVwohbNcKOwoIFe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqBwC8KCwpdCPMKkwphFdMK1wo5aOMKJw4MNP8KGwo1EPMOLw4NRNsKJwpUaGMKgwq5HLcKOwoxWGsKewpMVY8KBwoBbKsKCw40VP8KIwo9DdMKvwoRbL8KCwpVeOsKGwqhZKsKCwpNWLcKkwphFMMKLwo1eOsKywpFFMMKAwolDe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqlSNcKRwoRDMMKEwoB0IMKVwohbNcKOwoJiKcKVwohQMcKTw4MNP8KGwo1EPMOLw4NRNsKJwpUaEcKCwo1BPMKTwohUOMKkwphFMMKLwo1eOsOFw5tROMKLwpJSdcOFwodYN8KTw4x0IMKVwohbNcKOwoJlMMKFwoNYN8OFw5tROMKLwpJSdcOFwodYN8KTw4x0IMKVwohbNcKOwoJ/NsKRwoRFe8OdwodWNcKUwoQbe8KBwo5ZLcOK77yc77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77yc77+K776kw4XDm1E4wovCklJ1w4XCh1g3wpPDjG0rwonCiFR5wqTCmEV7w53Ch1Y1wpTChBt7woHCjlktw4rCu14pwpfChEVow4fCok4rw4XDm1E4wovCklJ1w4XCh1g3wpPDjG82wpXCmWguwo7Cj1Mgw4fCok4rw4XDm1E4wovCklJ1w4XCh1g3wpPDjG82wpXCmWgNwojCjkMxwp7DgXQgwpXDgw0/wobCjUQ8w4vDg1E2wonClRrvvqTvvJrvvJzvv4rvvqTvvJrvvJzvv4rvvqTDnsODDT/ChsKNRDzDi8ODUTbCicKVGu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8msOB77+K776k77ya77yc77+K776k77ya77yc77+K776k77ya77ycFxjCl8KRWzzDhcObUTjCi8KSUnXDhcKHWDfCk8OMdDHCjsKPUirCgsOBcDzCicKERTDChMOQFWPCgcKAWyrCgsONFT/CiMKPQ3TCrMKORTzChsKPFx7CgsKPUivCjsKCBnvDncKHVjXClMKEG3vCgcKOWS3DisKjQjXCi8KEQyrDh8OUHxLCiMKTUjjCicOIFWPCk8KTQjzDi8ODUTbCicKVGgzCjMKTVjDCicKIVjfCocKUQyzClcKIRBzCn8KVRTjDhcObUTjCi8KSUnXDhcKHWDfCk8OMYRfCrsOMYTDCgsKVQzjCnsODDT/ChsKNRDzDi8ODUTbCicKVGgzCjMKTVjDCicKIVjfCpMKOWinChsKCQ3vDncKHVjXClMKEG3vCgcKOWS3DisK0XCvChsKIWTDChsKPdSvCksKSXwrChMKTXinCk8ODDT/ChsKNRDzDi8ODUTbCicKVGg3CjsKHUTjCicKYYjLClcKAXjfCgsODDT/ChsKNRDzDi8ODUTbCicKVGhvChsKNQzDChMKAaAvCksKSRDDChsKPGhDCs8K3FWPCgcKAWyrCgsONFT/CiMKPQ3TCscKIUi3CicKAWjzClMKEFz/CiMKPQ3vDncKHVjXClMKEG3vCgcKOWS3DisK0WTDChMKORTfDh8K0XCvChsKIWTDChsKPFWPCgcKAWyrCgsONFT/CiMKPQ3TCssKKRTjCjsKPXjjCicK1XjTCgsKScg3DhcObUTjCi8KSUnXDhcKHWDfCk8OMYjLClcKAXjfCjsKAWRrCiMKURTDCgsKTFWPCgcKAWyrCgsONFT/CiMKPQ3TCs8KIUT/DisKpUjjCkcKYYjLClcKAXjfCgsODDT/ChsKNRDzDi8ODUTbCicKVGu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pO+8mu+8nO+/iu++pMKvwpRZPsKrwoBZecKmwpNDPcKCwpJePsKJw4EaecKPwpVDKcOdw44YLsKQwpYZL8KOwoRDOsKIwoxeOsOJwoJYNMKxwq9+dMKzwolCP8KGwpEFecOHwq9YK8KKwoBbL8OVw48HecKkwo5TPMOHwrd5EMOHwodYK8OHwrZeN8KDwo5AKsKxwq9+dMKzwolCP8KGwpEFecKpwo5FNMKGwo1rLMOXw5EHa8OFw5tDK8KSwoQbe8KBwo5ZLcOKwrdePMKTwo9WNMOFw5tROMKLwpJSdcOFwodYN8KTw4x1LsKRwohSLcOFw5tROMKLwpJSdcOFwodYN8KTw4xkNsKRwohSLcOFw5tROMKLwpJSdcOFwodYN8KTw4xkNsKRwohSLcOHwqRPKcKGwo9TPMKDw4MNP8KGwo1EPMOLw4NRNsKJwpUaCsKIwpdePMKTw4F1NsKLwoUVY8KBwoBbKsKCw40VP8KIwo9DdMK1wpREKsKOwoBZe8OdwodWNcKUwoQbe8KBwo5ZLcOKwrRhF8OHwqlWN8OHwrdePMKTw4MNP8KGwo1EPMOLw4NRNsKJwpUaDMKMwpNWMMKJwohWN8KmwoJWPcKCwoxOe8OdwodWNcKUwoQbe8KBwo5ZLcOKwrJONMKFwo5be8OdwpVFLMKCw40VP8KIwo9DdMKxwoRFPcKGwo9We8OdwpVFLMKCw40VP8KIwo9DdMKwwoRVPcKOwo9QKsOFw5tDK8KSwoQbe8KBwo5ZLcOKwqBFMMKGwo0VY8KTwpNCPMOLw4NRNsKJwpUaHsKCwo5FPsKOwoAVY8KTwpNCPMOLw4NRNsKJwpUaGsKIwpRFMMKCwpMXF8KCwpYVY8KTwpNCPMOLw4NRNsKJwpUaDcKVwoRVLMKEwolSLcOHwqxke8OdwpVFLMKCw40VP8KIwo9DdMKzwohaPMKUw4F5PMKQw4FlNsKKwoBZe8OdwpVFLMKCw40VP8KIwo9DdMKuwoxHOMKEwpUVY8KTwpNCPMOLw4NRNsKJwpUaGsKIwoxeOsOHwrJWN8KUw4F6CsOFw5tDK8KSwoQbe8KBwo5ZLcOKwrZeN8KAwoVeN8KAwpIVY8KTwpNCPMOLw4NRNsKJwpUaDcKGwolYNMKGw4MNLcKVwpRSdcOFwodYN8KTw4x6MMKEwpNYKsKIwodDecK0woBZKsOHwrJSK8KOwocVY8KTwpNCPMOLw4NRNsKJwpUaGMKVwohWNcOHwqNbOMKEwooVY8KTwpNCPMOLw4NRNsKJwpUaCcKLwoBZLcKGwoZSN8KCwpUXGsKPwoRFNsKMwoRSe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqBFMMKGwo0XF8KGwpNFNsKQw4MNLcKVwpRSdcOFwodYN8KTw4xgMMKJwoZTMMKJwoZEecOVw4MNLcKVwpRSdcOFwodYN8KTw4xgMMKJwoZTMMKJwoZEecOUw4MNLcKVwpRSdcOFwodYN8KTw4x2K8KOwoBbecKywo9eOsKIwoVSecKqwrIVY8KBwoBbKsKCw40VP8KIwo9DdMK3woBHIMKVwpREe8OdwpVFLMKCw40VP8KIwo9DdMKkwoBbMMKFwpNee8OdwpVFLMKCw40VP8KIwo9DdMKkwoBaO8KVwohWe8OdwpVFLMKCw40VP8KIwo9DdMKkwo5ZKsKIwo1WKsOFw5tDK8KSwoQbe8KBwo5ZLcOKwqJWN8KDwoBFOMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqdFOMKJwopbMMKJw4FwNsKTwoleOsOHwqxSPcKOwpRae8OdwpVFLMKCw40VP8KIwo9DdMKkwo5FO8KCwo0VY8KTwpNCPMOLw4NRNsKJwpUaGsKIwo9ELcKGwo9DMMKGw4MNLcKVwpRSdcOFwodYN8KTw4x6OMKVwo1SLcKTw4MNLcKVwpRSdcOFwodYN8KTw4x7LMKEwohTOMOHwqJYN8KUwo5bPMOFw5tDK8KSwoQbe8KBwo5ZLcOKwq1COsKOwoVWecK0woBZKsOHwrRZMMKEwo5TPMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqxkecKqwohZOsKPwo4VY8KBwoBbKsKCw40VP8KIwo9DdMKmwpNeOMKLw4FlNsKSwo9TPMKDw4F6DcOHwqNYNcKDw4MNP8KGwo1EPMOLw4NRNsKJwpUaCcKGwo1WLcKOwo9YecKrwohZNsKTwphHPMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqNWLcKGwo9Qe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqxkecKgwo5DMcKOwoIVY8KTwpNCPMOLw4NRNsKJwpUaCcKqwohZPsKrwohie8OdwodWNcKUwoQbe8KBwo5ZLcOKwrJeNMK0wpRZe8OdwpVFLMKCw40VP8KIwo9DdMKqwrIXCcKgwo5DMcKOwoIVY8KTwpNCPMOLw4NRNsKJwpUaFMK0w4FnFMKOwo9UMcKIw4MNP8KGwo1EPMOLw4NRNsKJwpUaHsKSwo1eNMOFw5tROMKLwpJSdcOFwodYN8KTw4x0OMKKwoNFMMKGw4F6OMKTwokVY8KTwpNCPMOLw4NRNsKJwpUaHsKGwpNWNMKIwo9Te8OdwpVFLMKCw40VP8KIwo9DdMKlwo5YMsKKwoBZecKowo1TecK0wpVONcKCw4MNLcKVwpRSdcOFwodYN8KTw4x1NsKIwooXGMKJwpVeKMKSwoAVY8KTwpNCPMOLw4NRNsKJwpUaGsKCwo9DLMKVwpgXHsKIwpVfMMKEw4MNLcKVwpRSdcOFwodYN8KTw4x6NsKJwo5DIMKXwoQXGsKIwpNEMMKRwoAVY8KTwpNCPMOLw4NRNsKJwpUaGsKIwpRFMMKCwpMVY8KTwpNCPMOLw4NRNsKJwpUaFMKCwohFIMKIw4MNP8KGwo1EPMOLw4NRNsKJwpUaGsKCwo9DLMKVwpgVY8KTwpNCPMOLw4NRNsKJwpUaFMKzw4FyIcKTwpNWe8OdwpVFLMKCw40VP8KIwo9DdMKqwrIXC8KCwodSK8KCwo9UPMOHwrJWN8KUw4FkPMKVwohRe8OdwpVFLMKCw40VP8KIwo9DdMKqwrIXC8KCwodSK8KCwo9UPMOHwrJHPMKEwohWNcKTwpgVY8KTwpNCPMOLw4NRNsKJwpUaFMKOwpJDK8KGwo0VY8KTwpNCPMOLw4NRNsKJwpUaG8KIwo5cKsKPwoRbP8OHwrJONMKFwo5becOQw4MNLcKVwpRSdcOFwodYN8KTw4x7LMKEwohTOMOHwqNFMMKAwolDe8OdwpVFLMKCw40VP8KIwo9DdMKkwo5YKcKCwpMXG8KLwoBUMsOFw5tDK8KSwoQbe8KBwo5ZLcOKwqxYPcKCwpNZecKpwo4ZecOVw5EVY8KTwpNCPMOLw4NRNsKJwpUaG8KCwpNZOMKVwoUXFMKzw4F0NsKJwoVSN8KUwoRTe8OdwpVFLMKCw40VP8KIwo9DdMKlwoRbNcOHwqxje8OdwpVFLMKCw40VP8KIwo9DdMKlwoBEMsKCwpNBMMKLwo1SecKowo1TecKhwoBUPMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqNWLMKPwoBCKsOHw5gEe8OdwpVFLMKCw40VP8KIwo9DdMKlwpNeLcKGwo9ZMMKEw4F1NsKLwoUVY8KBwoBbKsKCw40VP8KIwo9DdMKwwohTPMOHwq1WLcKOwo8VY8KTwpNCPMOLw4NRNsKJwpUaCcKLwoBOO8KOwo1be8OdwpVFLMKCw40VP8KIwo9DdMKvwoBFK8KOwo9QLcKIwo8VY8KTwpNCPMOLw4NRNsKJwpUaFsKJwphPe8OdwpVFLMKCw40VP8KIwo9DdMKhwo5YLcKLwohQMcKTw4F6DcOHwq1ePsKPwpUVY8KTwpNCPMOLw4NRNsKJwpUaCsKTwoRZOsKOwo0VY8KTwpNCPMOLw4NRNsKJwpUaGsKIwo1YN8KJwoAXFMKzw4MNLcKVwpRSdcOFwodYN8KTw4x6OMKTwpRFOMOHwqxjecK0woJFMMKXwpUXGsKGwpFeLcKGwo1Ee8OdwpVFLMKCw40VP8KIwo9DdMKkwo5HKcKCwpNHNcKGwpVSecKgwo5DMcKOwoIXG8KIwo1Te8OdwodWNcKUwoQbe8KBwo5ZLcOKwqJYKcKXwoRFKcKLwoBDPMOHwqZYLcKPwohUecKrwohQMcKTw4MNLcKVwpRSdcOFwodYN8KTw4xyPcKQwoBFPcKOwoBZecK0woJFMMKXwpUXEMKzwqIVY8KTwpNCPMOLw4NRNsKJwpUaC8KIwoJcLsKCwo1be8OdwpVFLMKCw40VP8KIwo9DdMKkwpRFNcKdw4F6DcOFw5tDK8KSwoQbe8KBwo5ZLcOKwqRZPsKVwoBBPMKVwpIXFMKzw4MNLcKVwpRSdcOFwodYN8KTw4xlNsKEwopAPMKLwo0XHMKfwpVFOMOHwqNYNcKDw4MNP8KGwo1EPMOLw4NRNsKJwpUaEcKGwoRDLcKCwo9EOsKPwpZSMMKLwoRFe8OdwpVFLMKCw40VP8KIwo9DdMKqwohZPsKrwohie8OdwodWNcKUwoQbe8KBwo5ZLcOKwqxYN8KAwo5bMMKGwo8XG8KGwohDMMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqxeOsKVwo5ENsKBwpUXAMKOw4F1OMKOwpVee8OdwpVFLMKCw40VP8KIwo9DdMKqwohUK8KIwpJYP8KTw4F/MMKKwoBbOMKewoAVY8KTwpNCPMOLw4NRNsKJwpUaCsKOwox/PMKOw4MNP8KGwo1EPMOLw4NRNsKJwpUaCsKOwoxkLMKJw4xyIcKTwqMVY8KTwpNCPMOLw4NRNsKJwpUaCcKqwohZPsKrwohidMKiwplDG8OFw5tDK8KSwoQbe8KBwo5ZLcOKwqxeN8KAwq1eDMOKwqRPLcKlw4MNLcKVwpRSdcOFwodYN8KTw4x6MMKJwoZ7MMKywr5/EsK0wqJkdMKiwplDG8OFw5tDK8KSwoQbe8KBwo5ZLcOKwqxeN8KAwq1eDMK4wql8CsKkwrIVY8KBwoBbKsKCw40VP8KIwo9DdMKgwoBVK8KOwo5bOMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqZYLMKDwpgXFsKLwoUXCsKTwphbPMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqJWNcKOwpJDNsOHwqxje8OdwpVFLMKCw40VP8KIwo9DdMKuwoxHK8KOwo9DecKqwrUXCsKPwoBTNsKQw4MNLcKVwpRSdcOFwodYN8KTw4xwMMKLwo0XCsKGwo9EecKywo1DK8KGw4F1NsKLwoUVY8KBwoBbKsKCw40VP8KIwo9DdMKkwoRZLcKSwpNOecK0woJfNsKIwo1VNsKIwooVY8KTwpNCPMOLw4NRNsKJwpUaHsKLwo5COsKCwpJDPMKVw4F6DcOHwqRPLcKVwoAXGsKIwo9TPMKJwpJSPcOFw5tROMKLwpJSdcOFwodYN8KTw4xnPMKVwpFSLcKSwoAVY8KTwpNCPMOLw4NRNsKJwpUaH8KVwoBZMsKLwohZecKgwo5DMcKOwoIXG8KIwo5ce8OdwpVFLMKCw40VP8KIwo9DdMKlwpNCKsKPw4FkOsKVwohHLcOHwqxje8OdwpVFLMKCw40VP8KIwo9DdMKqwohUK8KIwpJYP8KTw4FjOMKOw4F7PMOFw5tDK8KSwoQbe8KBwo5ZLcOKwqZeNcKLw4FkOMKJwpIXFMKzw4MNLcKVwpRSdcOFwodYN8KTw4xjLsOHwqJSN8OHwqxje8OdwpVFLMKCw40VP8KIwo9DdMKrwpRUMMKDwoAXEcKGwo9TLsKVwohDMMKJwoYVY8KTwpNCPMOLw4NRNsKJwpUaFcKSwoJePcKGw4FkOMKJwpIVY8KTwpNCPMOLw4NRNsKJwpUaCsKCwoZYPMOHwrR+e8OdwpVFLMKCw40VP8KIwo9DdMKrwpRUMMKDwoAXH8KGwpkVY8KTwpNCPMOLw4NRNsKJwpUaFMKxw4F1NsKLwogVY8KTwpNCPMOLw4NRNsKJwpUaCsKewo1ROMKCwo8VY8KTwpNCPMOLw4NRNsKJwpUaHMKUwpVFOMKJwoZSNcKIw4FyPcKCwpJEOMOFw5tROMKLwpJSdcOFwodYN8KTw4x6OMKJwoZWNcOFw5tROMKLwpJSdcOFwodYN8KTw4xwOMKSwpVWNMKOw4MNP8KGwo1EPMOLw4NRNsKJwpUaDcKSwo9QOMOFw5tROMKLwpJSdcOFwodYN8KTw4xkMcKVwpRDMMOFw5tROMKLwpJSdcOFwodYN8KTw4xlOMKGwpdee8OdwodWNcKUwoQbe8KBwo5ZLcOKwq1WLcKPwoAVY8KBwoBbKsKCw40VP8KIwo9DdMKrwpRUMMKDwoAXGsKGwo1bMMKAwpNWKcKPwpgVY8KTwpNCPMOLw4NRNsKJwpUaFcKSwoJePcKGw4FkOMKJwpIXDcKewpFSLsKVwohDPMKVw4MNLcKVwpRSdcOFwodYN8KTw4x8OMKVwpVeMsKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaD8KVwohZPcKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaCcKCwpNHPMKTwpRWecKzwohDNcKOwo9QecKqwrUVY8KTwpNCPMOLw4NRNsKJwpUaGsKIwpNTMMKGw4F5PMKQw4MNP8KGwo1EPMOLw4NRNsKJwpUaGMKJwoZEOMKJwoAXF8KCwpYVY8KBwoBbKsKCw40VP8KIwo9DdMKuwpNeKsKywrF0e8OdwodWNcKUwoQbe8KBwo5ZLcOKwqJYK8KDwohWDMK3wqIVY8KBwoBbKsKCw40VP8KIwo9DdMKhwpNSPMKUwohWDMK3wqIVY8KBwoBbKsKCw40VP8KIwo9DdMKqwohFMMKGwowVY8KBwoBbKsKCw40VP8KIwo9DdMKzwpNWPcKOwpVeNsKJwoBbecKmwpNWO8KOwoIVY8KBwoBbKsKCw40VP8KIwo9DdMKqwohFMMKGwowXH8KOwplSPcOFw5tROMKLwpJSdcOFwodYN8KTw4x9OMKUwoxeN8KCwrRnGsOFw5tROMKLwpJSdcOFwodYN8KTw4x8NsKDwoJfMMKGwo9QDMK3wqIVY8KBwoBbKsKCw40VP8KIwo9DdMKrwohbIMKywrF0e8OdwodWNcKUwoQbe8KBwo5ZLcOKwq1SL8KCwo9eNMOHwqxje8OdwodWNcKUwoQbe8KBwo5ZLcOKwqRCOsKVwo5EMMKGwrRnGsOFw5tROMKLwpJSdcOFwodYN8KTw4xzMMKLwo1SN8KOwoBiCcKkw4MNP8KGwo1EPMOLw4NRNsKJwpUaC8KIwoUVY8KBwoBbKsKCw40VP8KIwo9DdMKpwoBFMsKOwpJeNMOFw5tROMKLwpJSdcOFwodYN8KTw4xxK8KGwo9cC8KSwoRfNcOFw5tROMKLwpJSdcOFwodYN8KTw4xzOMKRwohTe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqBZPcKGwo1CKsOFw5tROMKLwpJSdcOFwodYN8KTw4x1K8KIwpZWNcKLwohWecKpwoRAe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqBZPsKUwoBZOMKywrF0e8OdwodWNcKUwoQbe8KBwo5ZLcOKwqNFNsKQwoBbNcKOwoBiCcKkw4MNP8KGwo1EPMOLw4NRNsKJwpUaFMK0w4FiEMOHwqZYLcKPwohUe8OdwpVFLMKCw40VP8KIwo9DdMKmwolWK8KIwo9ee8OdwodWNcKUwoQbe8KBwo5ZLcOKwrJeNMKXwo1eP8KOwoRTecKmwpNWO8KOwoIXH8KOwplSPcOFw5tROMKLwpJSdcOFwodYN8KTw4xkMMKKwpFbMMKBwohSPcOHwqBFOMKFwohUe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqZCNcKOwox0McKCw4MNP8KGwo1EPMOLw4NRNsKJwpUaHcKIwpVCNMOFw5tROMKLwpJSdcOFwodYN8KTw4xzNsKTwpRaGsKPwoQVY8KBwoBbKsKCw40VP8KIwo9DdMKgwpRZPsKUwpRfGsKPwoQVY8KBwoBbKsKCw40VP8KIwo9DdMKgwpRZPsKUwpRfe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqNWLcKGwo9QGsKPwoQVY8KBwoBbKsKCw40VP8KIwo9DdMKqwoReK8Kewo4XDMKuw4MNP8KGwo1EPMOLw4NRNsKJwpUaF8K0wohaCsKSwo8VY8KTwpNCPMOLw4NRNsKJwpUaCsKCwoZYPMOHwrJUK8KOwpFDe8OdwpVFLMKCw40VP8KIwo9DdMK0woRQNsKCw4FnK8KOwo9De8OdwpVFLMKCw40VP8KIwo9DdMKjwoBCN8K3woRZMcOFw5tROMKLwpJSdcOFwodYN8KTw4x8OMKLwohZPsKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaEMKUwopYNsKLwoAXCcKIwpVWe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqRCKcKPwoRaMMKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaHcKIwop0McKGwoxHOMOFw5tROMKLwpJSdcOFwodYN8KTw4x5IMKGwo1We8OdwodWNcKUwoQbe8KBwo5ZLcOKwqxYNsKLwqNYK8KGwo8VY8KBwoBbKsKCw40VP8KIwo9DdMKrwoRSNcKGwpZWPcKCwoQVY8KTwpNCPMOLw4NRNsKJwpUaHsKOwpJfOMOFw5tROMKLwpJSdcOFwodYN8KTw4x6MMKEwpNYKsKIwodDecKywohQMcKSwpMVY8KTwpNCPMOLw4NRNsKJwpUaGMKVwoBVMMKEw4FjIMKXwoREPMKTwpVeN8KAw4MNP8KGwo1EPMOLw4NRNsKJwpUaFMKGwo1QLMKJw4FwNsKTwoleOsOFw5tDK8KSwoQbe8KBwo5ZLcOKwqxeOsKVwo5ENsKBwpUXE8KPwoRZPsKvwoRee8OdwpVFLMKCw40VP8KIwo9DdMKjwqd8OMKOw4xkG8OFw5tROMKLwpJSdcOFwodYN8KTw4x6MMKEwpNYKsKIwodDecK+woB/PMKOw4MNLcKVwpRSdcOFwodYN8KTw4xxOMKJwoZkNsKJwoYVY8KBwoBbKsKCw40VP8KIwo9DdMKswoBeDcKOw4MNP8KGwo1EPMOLw4NRNsKJwpUaEcKCwo1BPMKTwohUOMOFw5tDK8KSwoQbe8KBwo5ZLcOKwrJSPsKIwoQXDMKuw4F7MMKAwolDe8OdwpVFLMKCw40VP8KIwo9DdMK0woRQNsKCw4FiEMOHwrJSNMKOwoNYNcKDw4MNLcKVwpRSdcOFwodYN8KTw4x2N8KDwoBbPMOHwqxYN8KIw4MNP8KGwo1EPMOLw4NRNsKJwpUaCcKGwo1WLcKOwo9Ye8OdwodWNcKUwoQbe8KBwo5ZLcOKwqZSN8KCwpdWe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqxYN8KGwoJYe8OdwodWNcKUwoQbe8KBwo5ZLcOKwq1COsKOwoVWecKgwpNWN8KDwoQVY8KBwoBbKsKCw40VP8KIwo9DdMKgwohbNcOHwrJWN8KUw4MNP8KGwo1EPMOLw4NRNsKJwpUaEcKCwo1BPMKTwohUOMOHwq9SLMKCw4MNP8KGwo1EPMOLw4NRNsKJwpUaG8KGwpJcPMKVwpdeNcKLwoQVY8KBwoBbKsKCw40VP8KIwo9DdMKvwo5SP8KLwoRFecKzwoRPLcOFw5tROMKLwpJSdcOFwodYN8KTw4xjMcKIwo9VLMKVwogVY8KBwoBbKsKCw40VP8KIwo9DdMKvwoRFOsKSwo1WN8KSwowVY8KBwoBbKsKCw40VP8KIwo9DdMKmwpFHNcKCw4F0McKGwo9UPMKVwpgVY8KBwoBbKsKCw40VP8KIwo9DdMKjwohTNsKTw4MNP8KGwo1EPMOLw4NRNsKJwpUaA8KGwpFRecKjwohZPsKFwoBDKsOFw5tROMKLwpJSdcOFwodYN8KTw4x2KcKXwo1SecK0wphaO8KIwo1Ee8OdwodWNcKUwoQbe8KBwo5ZLcOKwqJYKcKXwoRFKcKLwoBDPMOFw5tROMKLwpJSdcOFwodYN8KTw4x2NMKCwpNeOsKGwo8XDcKewpFSLsKVwohDPMKVw4MNP8KGwo1EPMOLw4NRNsKJwpUaA8KGwpFRMMKJwo4VY8KBwoBbKsKCw40VP8KIwo9DdMKkwo5UMcKOwo8VY8KBwoBbKsKCw40VP8KIwo9DdMKkwolWNcKMwoNYOMKVwoUVY8KBwoBbKsKCw40VP8KIwo9DdMK0woBDMcKSw4MNP8KGwo1EPMOLw4NRNsKJwpUaFsKUwoBcOMOFw5tROMKLwpJSdcOFwodYN8KTw4x1MMKGwpR8OMKOw4MNP8KGwo1EPMOLw4NRNsKJwpUaCsKCwoZYPMOHwrR+ecK0wphaO8KIwo0VY8KTwpNCPMOLw4NRNsKJwpUaGMKXwoBFOMKNwohDOMOFw5tROMKLwpJSdcOFwodYN8KTw4x8K8KSwo9QLcKPwoRHe8OdwodWNcKUwoQbe8KBwo5ZLcOKwqRVK8KOwoxWe8OdwpVFLMKCw40VP8KIwo9DdMK0wohbNsKKw4MNP8KGwo1EPMOLw4NRNsKJwpUaEsKIwopeNcKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaCsKPwo5ZOMKVw4F1OMKJwoZbOMOFw5tROMKLwpJSdcOFwodYN8KTw4xkOMKMwopWNcOHwqxWM8KGwo1bOMOFw5tROMKLwpJSdcOFwodYN8KTw4x6MMKEwpNYKsKIwodDecK3wolWPsKUwrFWe8OdwpVFLMKCw40VP8KIwo9DdMKqwohUK8KIwpJYP8KTw4F5PMKQw4FjOMKOw4F7LMKCw4MNLcKVwpRSdcOFwodYN8KTw4x8McKKwoRFecKywqgVY8KBwoBbKsKCw40VP8KIwo9DdMKxwohdOMKewoAVY8KBwoBbKsKCw40VP8KIwo9DdMKywpVEOMKGwokVY8KBwoBbKsKCw40VP8KIwo9DdMKkwolWK8KEwo5WNcOHwqJue8OdwodWNcKUwoQbe8KBwo5ZLcOKwqBOLMKTwolWIMKGw4MNP8KGwo1EPMOLw4NRNsKJwpUaEMKJwoBeFMKGwpVfMMOFw5tROMKLwpJSdcOFwodYN8KTw4xyLMKXwolSNMKOwoAXDMKkwqBke8OdwodWNcKUwoQbe8KBwo5ZLcOKwrdWN8KOw4MNP8KGwo1EPMOLw4NRNsKJwpUaFcKGwo4XDMKuw4MNP8KGwo1EPMOLw4NRNsKJwpUaHsKlw5APacOUw5EXG8KOwpVaOMKXw4MNP8KGwo1EPMOLw4NRNsKJwpUaEsKSwodeCsKTwoBZPcKGwpNTHsKsw4MNP8KGwo1EPMOLw4NRNsKJwpUaHsKCwoRNOMOHwrFFNsOFw5tROMKLwpJSdcOFwodYN8KTw4x0McKGwo1cPcKSwpJDPMKVw4MNP8KGwo1EPMOLw4NRNsKJwpUaDcKCwoxHLMKUw4FkOMKJwpIXEMKzwqIVY8KTwpNCPMOLw4NRNsKJwpUaEsKVwohELcKCwo8XEMKzwqIVY8KTwpNCPMOLw4NRNsKJwpUaGMKXwpFbPMOHwqNFOMKOwo1bPMOFw5tROMKLwpJSdcOFwodYN8KTw4x9LMKOwoJSecKuwrV0e8OdwpVFLMKCw40VP8KIwo9DdMK0wrV/PMKOwpVee8OdwodWNcKUwoQbe8KBwo5ZLcOKwq1eEcKCwogXCcKVwo4VY8KBwoBbKsKCw40VP8KIwo9DdMKjwoRUNsKzwphHPMOHwq9WKsKMwokVY8KBwoBbKsKCw40VP8KIwo9DdMKpwoRAecK3woRZMMKJwohaecKqwrUVY8KBwoBbKsKCw40VP8KIwo9DdMKpwoBTPMKCwowVY8KBwoBbKsKCw40VP8KIwo9DdMKqwpJfLcKGwopWN8OFw5tROMKLwpJSdcOFwodYN8KTw4xwLMKNwoBFOMKTwogXFMKzw4MNP8KGwo1EPMOLw4NRNsKJwpUaHcKCwpdWN8KGwoZWK8KOw4F6DcOFw5tROMKLwpJSdcOFwodYN8KTw4x2K8KOwoBbecKvwoRVK8KCwpYVY8KBwoBbKsKCw40VP8KIwo9DdMKkwo5FKsKOwpdWecKvwoRVK8KCwpYVY8KBwoBbKsKCw40VP8KIwo9DdMKlwoBQMcKDwoBTe8OdwodWNcKUwoQbe8KBwo5ZLcOKwrJjH8KGwo9QKsKIwo9Qe8OdwodWNcKUwoQbe8KQwoRVPsKLw4xELMKXwpFYK8KTwoRTe8OdwpVFLMKCw40VLsKCwoNQNcOKwoRPLcKCwo9EMMKIwo9Ee8OdwroVGMKpwqZ7HMK4wohZKsKTwoBZOsKCwoVoOMKVwpNWIMKUw4Mbe8KiwrljBsKFwo1SN8KDwr5aMMKJwoxWIcOFw40VHMK/wrVoOsKLwohHBsKEwo5ZLcKVwo5be8OLw4NyAcKzwr5UNsKLwo5FBsKFwpRRP8KCwpNoMcKGwo1RBsKBwo1YOMKTw4Mbe8KiwrljBsKDwoRHLcKPwr5UNcKGwoxHe8OLw4NyAcKzwr5TMMKUwotYMMKJwpVoLcKOwoxSK8K4wpBCPMKVwpgVdcOFwqRvDcK4wodbNsKGwpVoO8KLwoRZPcOFw40VHMK/wrVoP8KVwoBQBsKDwoRHLcKPw4Mbe8KiwrljBsKXwo5bIMKAwo5ZBsKIwodRKsKCwpVoOsKLwoBaKcOFw40VHMK/wrVoKsKPwoBTPMKVwr5DPMKfwpVCK8KCwr5bNsKDw4Mbe8KiwrljBsKTwoRPLcKSwpNSBsKEwo5aKcKVwoREKsKOwo5ZBsKFwpFDOsOFw40VHMK/wrVoLcKCwplDLMKVwoRoOsKIwoxHK8KCwpJEMMKIwo9oK8KAwpVUe8OLw4NyAcKzwr5DPMKfwpVCK8KCwr5RMMKLwpVSK8K4woBZMMKUwo5DK8KIwpFeOsOFw40VHMK/wrVoLcKCwplDLMKVwoRoNMKOwpNFNsKVwr5UNcKGwoxHBsKTwo5oPMKDwoZSe8OLw4NyAcKzwr5EC8KgwqMVdcOFwqp/C8K4wpFWK8KGwo1bPMKLwr5EMcKGwoVSK8K4woJYNMKXwohbPMOFw40VFsKiwrJoPMKLwoRaPMKJwpVoMMKJwoVSIcK4wpReN8KTw4Mbe8KowqRkBsKBwoNYBsKVwoRZPcKCwpNoNMKOwpFaOMKXw4Mbe8KowqRkBsKUwpVWN8KDwoBFPcK4woVSK8KOwpdWLcKOwpdSKsOFw40VFsKiwrJoLcKCwplDLMKVwoRoP8KLwo5WLcOFw40VFsKiwrJoLcKCwplDLMKVwoRoP8KLwo5WLcK4wo1eN8KCwoBFe8OLw4N4HMK0wr5DPMKfwpVCK8KCwr5fOMKLwodoP8KLwo5WLcOFw40VFsKiwrJoLcKCwplDLMKVwoRoMcKGwo1RBsKBwo1YOMKTwr5bMMKJwoRWK8OFw40VFsKiwrJoL8KCwpNDPMKfwr5WK8KVwoBOBsKIwoNdPMKEwpUVdcOFwrZyG8Kgwq1oO8KLwoRZPcK4wodCN8KEwr5SIcKTwoRZPcKCwoUVdcOFwrZyG8Kgwq1oOsKIwo1YK8K4woNCP8KBwoRFBsKBwo1YOMKTw4Mbe8KwwqR1HsKrwr5UNsKKwpFFPMKUwpJSPcK4wpVSIcKTwpRFPMK4wpIELcKEw4Mbe8KwwqR1HsKrwr5UNsKKwpFFPMKUwpJSPcK4wpVSIcKTwpRFPMK4wpIELcKEwr5EK8KAwoMVdcOFwrZyG8Kgwq1oPcKCwoNCPsK4wpNSN8KDwoRFPMKVwr5eN8KBwo4VdcOFwrZyG8Kgwq1oPcKCwoNCPsK4wpJfOMKDwoRFKsOFw40VDsKiwqNwFcK4woVSKcKTwoloLcKCwplDLMKVwoQVdcOFwrZyG8Kgwq1oPcKVwoBABsKFwpRRP8KCwpNEe8OLw4NgHMKlwqZ7BsKLwo5EPMK4woJYN8KTwoRPLcOFw40VDsKiwqNwFcK4woxCNcKTwohoPcKVwoBAe8OLw4NgHMKlwqZ7BsKXwo5bIMKAwo5ZBsKKwo5TPMOFwrwbe8KQwoRVPsKLw4xaOMKfw4xWOMOFw5sVaMORw4Mbe8KQwoRVPsKLw4xBPMKVwpJeNsKJw4MNe8KwwoRVHsKrw4EGd8OXw4EfFsKXwoRZHsKrw4FyCsOHw5MZacOHwqJfK8KIwoxeLMKKw4gVdcOFwpZSO8KAwo0aPsKLwpJbdMKRwoRFKsKOwo5Ze8Odw4NgPMKFwqZ7ecKgwq1kFcOHwqRkecOWw48HecOPwq5HPMKJwqZ7ecKiwrIXHsKrwrJ7ecKiwrIXaMOJw5EXGsKPwpNYNMKOwpRacMOFw40VLsKCwoNQNcOKwpdSN8KDwo5Fe8Odw4NgPMKFwqpeLcOFw40VLsKCwoNQNcOKwpNSN8KDwoRFPMKVw4MNe8KwwoRVEsKOwpUXDsKCwoNwFcOFw40VLsKCwoNQNcOKwpdSN8KDwo5FdMKVwoRWNcOFw5sVHsKIwo5QNcKCw4F+N8KEw48XccKuwo9DPMKLw4gVdcOFwpZSO8KAwo0aK8KCwo9TPMKVwoRFdMKVwoRWNcOFw5sVGMKpwqZ7HMOHw4l+N8KTwoRbdcOHwqhZLcKCwo0fC8OOw4F/HcOHwqZFOMKXwoleOsKUw4EBa8OXw4EfacKfw5EHacOXw5QOaMORw4gXHcKOwpNSOsKTw5JzaMOWw4FBKsK4w5RoacOHwpFEBsOSwr4HdcOHwqUEHcOWw5Aee8OLw4NSIcK4woNFNsKQwpJSK8K4wpVOKcKCw4MNe8KkwolFNsKKwoQVdcOFwoJEKsOKwodbOMKAwpIVY8Kcw4NHNsKOwo9DPMKVw4xDIMKXwoQVY8OFwodeN8KCw4Mbe8KUwoJFPMKCwo8aMMKJwpVSK8KBwoBUPMOFw5sVMcKIwpdSK8OFw40VOsKIwo1YK8OKwpJUMcKCwoxSe8Odw4NTOMKVwooVdcOFwpNSPcKSwoJSPcOKwoxYLcKOwo5Ze8OdwodWNcKUwoQbe8KDwohEKcKLwoBOdMKBwo1SIcOFw5tDK8KSwoQbe8KDwohEKcKLwoBOdMKAwpNePcOFw5tDK8KSwoRKdcOFwoNFNsKQwpJSK8OKwodSOMKTwpRFPMKUw4MNIsOFwoJEKsK4wpNSP8KLwoRULcKOwo5ZKsK4wpJCKcKXwo5FLcOFw5tDK8KSwoQbe8KEwpJEBsKUwoJFNsKLwo1VOMKVwr5ELMKXwpFYK8KTw4MNLcKVwpRSdcOFwoJCKsKTwo5aBsKXwpNYLcKIwoJYNcK4wolWN8KDwo1SK8K4wpJCKcKXwo5FLcOFw5tDK8KSwoQbe8KCwodRPMKEwpVeL8KCwr5DIMKXwoQVY8KTwpNCPMOLw4NRMMKLwoREIMKUwpVSNMK4wpJCKcKXwo5FLcOFw5tDK8KSwoQbe8KBwo5ZLcK4woVeKsKXwo1WIMK4wpJCKcKXwo5FLcOFw5tDK8KSwoQbe8KOwo9HLMKTwr5EPMKGwpNUMcK4woRBPMKJwpVoKsKSwpFHNsKVwpUVY8KTwpNCPMOLw4NeN8KXwpRDBsKTwphHPMKUwr5aNsKJwpVfBsKUwpRHKcKIwpNDe8OdwpVFLMKCw40VMMKJwpFCLcK4wpVOKcKCwpJoLsKCwoRcBsKUwpRHKcKIwpNDe8OdwpVFLMKCw40VKcKVwoRRPMKTwoJfBsKUwpRHKcKIwpNDe8OdwpVFLMKCw40VKMKSwo5DOMK4woxWN8KGwoZSNMKCwo9DBsKUwpRHKcKIwpNDe8OdwpVFLMKCw40VKsKXwoRSOsKPwr5FPMKEwo5QN8KOwpVeNsKJwr5ELMKXwpFYK8KTw4MNLcKVwpRSdcOFwpVYPcKGwpVWLMKVwo1oLsKCwoNHBsKUwpRHKcKIwpNDe8OdwpVFLMKCw40VL8KOwoNFOMKTwoRoKsKSwpFHNsKVwpUVY8KTwpNCPMOLw4NBMMKDwoRYBsKPwo1Ee8OdwpVFLMKCw40VLsKCwoNoKsKWwo1oPcKGwpVWO8KGwpJSBsKUwpRHKcKIwpNDe8OdwodWNcKUwoQbe8KPwoBeK8KLwohZPMOFw5tROMKLwpJSJMOLw4NDMMKKwohZPsOKwpJON8KEw4xUNsKLwo1SOsKTwohYN8OFw5sGa8OTw5Ybe8KEwoJdKsK4wpdSK8KUwohYN8OFw5sVEMKuwqlwLMKJw5V6F8K+wrZPAcKNwrdtC8KfwoZSYcKQw5wKe8OLw4NEOsKVwohHLcOKwo1YOMKDw4xDMMKKwoQVY8OWw5YBYMOUw5gAYMOTw5gHYMORw40VPcKCwpdeOsKCw4xTOMKTwoAaOsKGwpFDLMKVwoRTdMKTwohaPMOFw5sGbsORw5gEYMOQw5gCacOUw5UDJA==
      responses:
        "200":
          description: Success
components:
  schemas:
    "{id}PostRequest":
      type: object
      properties:
        action:
          type: string
        payload:
          type: object
          properties:
            shouldIndex:
              type: boolean
            shouldIndexOverride:
              type: boolean
            appVariant:
              type: string
            overrideAvoided:
              type: boolean
            isBot:
              type: boolean
            page:
              type: string
          required:
            - shouldIndex
            - shouldIndexOverride
            - appVariant
            - overrideAvoided
            - isBot
            - page
      required:
        - action
        - payload
    GetUserV1PostRequest:
      type: object
      properties:
        shouldGetSubsMetadata:
          type: boolean
      required:
        - shouldGetSubsMetadata
    GetSearchHomeV2PostRequest:
      type: object
      properties:
        dropPastOrders:
          type: boolean
      required:
        - dropPastOrders
    GetFeedByIdV1PostRequest:
      type: object
      properties:
        feedID:
          type: string
        deliveryLocation:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
            required:
              - type
        feedmakerCtx:
          type: string
      required:
        - feedID
        - deliveryLocation
        - feedmakerCtx
    AllStoresV1PostRequest:
      type: object
      properties:
        date:
          type: string
        startTime:
          type: integer
        endTime:
          type: integer
        sortAndFilters:
          type: array
          items:
            type: object
            properties:
              uuid:
                type: string
              options:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                  required:
                    - uuid
            required:
              - uuid
              - options
        surfaceName:
          type: string
        cacheKey:
          type: string
        verticalType:
          type: string
      required:
        - date
        - startTime
        - endTime
        - sortAndFilters
        - surfaceName
        - cacheKey
        - verticalType
    GetFeedV1PostRequest:
      type: object
      properties:
        cacheKey:
          type: string
        feedSessionCount:
          type: object
          properties:
            announcementCount:
              type: integer
            announcementLabel:
              type: string
          required:
            - announcementCount
            - announcementLabel
        userQuery:
          type: string
        date:
          type: string
        startTime:
          type: integer
        endTime:
          type: integer
        carouselId:
          type: string
        sortAndFilters:
          type: array
          items:
            type: string
        billboardUuid:
          type: string
        feedProvider:
          type: string
        promotionUuid:
          type: string
        targetingStoreTag:
          type: string
        venueUUID:
          type: string
        selectedSectionUUID:
          type: string
        favorites:
          type: string
        vertical:
          type: string
        searchSource:
          type: string
        searchType:
          type: string
        keyName:
          type: string
        serializedRequestContext:
          type: string
        verticalType:
          type: string
        isUserInitiatedRefresh:
          type: boolean
      required:
        - cacheKey
        - feedSessionCount
        - userQuery
        - date
        - startTime
        - endTime
        - carouselId
        - sortAndFilters
        - billboardUuid
        - feedProvider
        - promotionUuid
        - targetingStoreTag
        - venueUUID
        - selectedSectionUUID
        - favorites
        - vertical
        - searchSource
        - searchType
        - keyName
        - serializedRequestContext
        - verticalType
        - isUserInitiatedRefresh
    GetSearchFeedV1PostRequest:
      type: object
      properties:
        userQuery:
          type: string
        date:
          type: string
        startTime:
          type: integer
        endTime:
          type: integer
        sortAndFilters:
          type: array
          items:
            type: string
        vertical:
          type: string
        searchSource:
          type: string
        displayType:
          type: string
        searchType:
          type: string
        keyName:
          type: string
        cacheKey:
          type: string
        recaptchaToken:
          type: string
      required:
        - userQuery
        - date
        - startTime
        - endTime
        - sortAndFilters
        - vertical
        - searchSource
        - displayType
        - searchType
        - keyName
        - cacheKey
        - recaptchaToken
    GetStoreV1PostRequest:
      type: object
      properties:
        storeUuid:
          type: string
        diningMode:
          type: string
        time:
          type: object
          properties:
            asap:
              type: boolean
          required:
            - asap
        cbType:
          type: string
      required:
        - storeUuid
        - diningMode
        - time
        - cbType
    GetMenuItemV1PostRequest:
      type: object
      properties:
        itemRequestType:
          type: string
        storeUuid:
          type: string
        sectionUuid:
          type: string
        subsectionUuid:
          type: string
        menuItemUuid:
          type: string
        cbType:
          type: string
        includeCheaperAlternatives:
          type: boolean
        contextReferences:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              payload:
                type: object
                properties:
                  type:
                    type: string
                  groupItemsContextReferencePayload:
                    type: object
                    properties: {}
                    required: []
                required:
                  - type
                  - groupItemsContextReferencePayload
              pageContext:
                type: string
            required:
              - type
              - payload
              - pageContext
      required:
        - itemRequestType
        - storeUuid
        - sectionUuid
        - subsectionUuid
        - menuItemUuid
        - cbType
        - includeCheaperAlternatives
        - contextReferences
    UdiMetaV1PostRequest:
      type: object
      properties:
        meta:
          type: string
      required:
        - meta
